### ISSUE TITLE
Elm 0.19

### ISSUE THREAD

**Issue by optikfluffel** [vic/asdf-elm#3]
Would be nice if `0.19` would be supported. ❤️

**Comment by benreyn** [comment]
Technically elm 0.19 is not officially released yet, but you can get it via `asdf install elm master` (I believe)

**Comment by optikfluffel** [comment]
I'm [not sure that's true](https://github.com/elm/compiler/releases/tag/0.19.0).

**Comment by benreyn** [comment]
Well will you look at that 😄 Thats exciting. So it looks like...

A. the compiler for 0.19 is released but the 0.19 version of [`elm-platform`](https://github.com/elm-lang/elm-platform) which this asdf plugin keys off of is not released?

B. This looks to be un-maintained 😞 Ref: https://github.com/vic/asdf-elm/commit/0e126a9d1768fc340abdc5640acec94f82a65800

**Comment by optikfluffel** [comment]
A. Maybe `elm-platform` just isn't needed anymore, since all the included stuff now lives directly [inside the elm binary](https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md#command-line).

B. The liked Twitter account is also suspended. 😕

**Comment by ashton** [comment]
There is already a [blog post](http://elm-lang.org/blog/small-assets-without-the-headache) and also the [link](https://github.com/elm/compiler/releases/download/0.19.0/installer-for-mac.pkg) in the site was updated to the 0.19.

**Comment by itsgreggreg** [comment]
Elm isn't using bintray anymore : https://discourse.elm-lang.org/t/any-plans-to-update-the-elmlang-bintray/1763

They are using github releases now: https://github.com/elm/compiler/releases

But only 19 has the compiled binaries in github releases, so we'd still need to keep the bintray code functional unless someone wants to find a new place to host _all_ the binaries.

**Comment by chazsconi** [comment]
I've created PR #4 that fetches < 0.19.0 releases from bintray, but later ones from github.

**Comment by chazsconi** [comment]
@vic Can this issue now be closed?

**Comment by vic** [comment]
@chazsconi Hm, the build is no passing on linux (previously we had an upstream bug in asdf plugin-test) .. now, the thing is I merged your PR without realizing the code in list-all now depends on `jq`, could you remove that dependency and send another PR ?

**Comment by vic** [comment]
https://travis-ci.org/vic/asdf-elm/jobs/423717416#L128

**Comment by andys8** [comment]
Issue can be closed and `0.19.0` is supported. #4 and #5 were merged.
